### ISSUE TITLE
Highlight around color column drawn incorrectly with signcolumn changes

### ISSUE THREAD

**Issue by bwells** [lukas-reineke/virt-column.nvim#1]
Thanks for the plugin, I like being able to clean up the look of my setup that little bit. 

I've found a bug, and I'm not sure if it's a Neovim or virt-column bug, in which a gap in the highlighting of `cursorline` is not drawn on the correct column as the sign column opens or closes with `signcolumn=auto`. I can provide a minimal config to reproduce if desired, but hopefully the included image is worth the proverbial thousand words. The color column values are redrawn correctly once the buffer scrolls vertically. 

##### Correct
<img width="816" alt="Correct colorcolumn" src="https://user-images.githubusercontent.com/468132/143594026-7ada5559-0e20-482d-a610-7ea315050de4.png">

##### Incorrect
<img width="822" alt="Incorrect colorcolumn" src="https://user-images.githubusercontent.com/468132/143593664-b8c4c605-53ae-4705-87f3-8361d462e402.png">

**Comment by lukas-reineke** [comment]
To position the column, I need to measure the whole window. The signcolumn width matters too.
But there is no autocommand that triggers when the size of the signcolumn changes, so I can't fix this.

But if you know what plugins update your signcolumn, you can run `:VirtColumnRefresh` with autocommands they provide.

For example, if you display LSP diagnostics signs, you can do this

```vim
autocmd DiagnosticChanged * VirtColumnRefresh
```

**Comment by francium** [comment]
A similar thing also occurs when you resize the split or terminal
![Peek 2021-11-26 12-04](https://user-images.githubusercontent.com/15352422/143613197-202424d4-01b1-4631-987a-84c4c739c04e.gif)

**Comment by francium** [comment]
`:VirtColumnRefresh` does this
![Peek 2021-11-26 12-06](https://user-images.githubusercontent.com/15352422/143613374-2d986f17-e95f-4be3-986a-85e1a9a977b9.gif)
I'm switching focus between the two splits here and re-running the command, in case it's hard to tell

**Comment by lukas-reineke** [comment]
I can't reproduce this :thinking: 
can you try if this fixes it? https://github.com/lukas-reineke/virt-column.nvim/pull/3

**Comment by francium** [comment]
No, still occurs, `PlugSnapshot` reports your fix branch commit, `4c5d8dac` is indeed installed.
Interesting you say you can't reproduce, perhaps I'll checkout your dotfiles and run them up to see if it's something in mine.

**Comment by lukas-reineke** [comment]
What terminal are you using?

**Comment by francium** [comment]
gnome-terminal on gnome

**Comment by lukas-reineke** [comment]
ohh no I understand now. They are both the same file :thinking: 

I did not think about that. There can't be different virtual text in the same buffer based on the window it is in..

**Comment by francium** [comment]
![Peek 2021-11-29 21-45](https://user-images.githubusercontent.com/15352422/143976704-b991996f-8de6-4f63-86c4-29fe333642c2.gif)

Here's two different files. Still a bit buggy.

**Comment by lukas-reineke** [comment]
Have you tried #3 with different buffers?

**Comment by francium** [comment]
Gif above is with #3

**Comment by francium** [comment]
Honestly it's usable, it'd be great if it was just that much better, but I'd accept it as something that can't be fixed due to limited vim APIs or events to work with.

**Comment by lukas-reineke** [comment]
I pushed an update to #3, can you check again?

**Comment by francium** [comment]
No, still have one buffer's column stuck until you move focus into it with your 931f1 commit into #3

**Comment by francium** [comment]
Are you running MacOS + iterm2 or something like that?

**Comment by lukas-reineke** [comment]
> Are you running MacOS + iterm2 or something like that?

arch + kitty

I made another update, I think this is as good as it gets.
This should fix all issues with different buffers, but having the same buffer open twice in different sized windows will never look good :cry: 
It should at least display the active buffer correct now.

Can you test again?

**Comment by lukas-reineke** [comment]
I think I actually manged to fix all issues now

**Comment by francium** [comment]
I'll test in a few mins.

**Comment by francium** [comment]
Now column 0 has the virtual column symbol and cursor while it's at col 0 is hidden
![image](https://user-images.githubusercontent.com/15352422/144166420-384508c4-47ca-476f-8536-ddc9b248a831.png)

Latest master branch. Haven't changed anything else in my config (was I suppose to?)

**Comment by francium** [comment]
Issue I've described in previous comment occurs first at 6a751013eba524d57505b4203ce555229e13a641 and is also present in master (7b013a2c873df8e1ec9412532b5ac7592d35a61d)

**Comment by lukas-reineke** [comment]
@francium you need the latest version of Neovim

**Comment by francium** [comment]
Got 0.6 on Arch.
Yeah, definitely much better now. Thanks.
