### ISSUE TITLE
Disable for certain type of files

### ISSUE THREAD

**Issue by zoriya** [lukas-reineke/virt-column.nvim#18]
Currently, the virtual column is shown on every window. It would be nice to disable certain windows like Telescope, NerdTree, the terminal etc...

**Comment by lukas-reineke** [comment]
You can already do this with filetype plugins.

Just turn of colorcolumn in `ftplugin/foo.lua` were `foo` is the filetype you want.
Just like vanilla Neovim

**Comment by zoriya** [comment]
Yes but you can't disable the `virtcolumn` argument of the setup method.

If I use the default colorcolumn property, the background of the color column is set to the default background of my theme, so it breaks highlights. This is not the case with the virtcolumn property. If you know how to disable this weird highligth, please let me know.

Picture of said highlight:
![image](https://user-images.githubusercontent.com/32224410/152793068-1cd6832b-67fc-4085-8184-baa9a2b00bfe.png)

**Comment by megalithic** [comment]
I am running into this with markdown files and I had to completely uninstall virt-column 😢 

I love this plugin, but reaaaaally need my highlighting in markdown files to not break. I'm happy to help troubleshoot, @lukas-reineke , if you ever wanted to tackle this.

**Comment by lukas-reineke** [comment]
Sorry, I forgot to comment here. Since [1.5.0](https://github.com/lukas-reineke/virt-column.nvim/releases/tag/v1.5.0) there is a `setup_buffer` function that you can use to configure a buffer.
If you are using the `virtcolumn` argument instead, use an autocmd or ftplugin with `setup_buffer` to overwrite the settings for specific filetypes.

**Comment by megalithic** [comment]
> Sorry, I forgot to comment here. Since [1.5.0](https://github.com/lukas-reineke/virt-column.nvim/releases/tag/v1.5.0) there is a `setup_buffer` function that you can use to configure a buffer. If you are using the `virtcolumn` argument instead, use an autocmd or ftplugin with `setup_buffer` to overwrite the settings for specific filetypes.

Thanks for the response Lukas! I feel really bone-headed; I'm not seeing how to actually "disable" everything about virt-column for markdown files, for instance; using `setup_buffer()`.  Any thoughts around that type of a use-case?

**Comment by lukas-reineke** [comment]
There are 2 cases

1. You are using `vim.opt.colorcolumn`
  In this case, you want to do `vim.opt_local.colorcolumn = ""` in the markdown ftplugin
2. You are using the `virtcolumn` argument in the setup function
  In this case, you want to do `require("virt-column").setup_buffer { virtcolumn = "" }` in the markdown ftplugin
