### ISSUE TITLE
Sorry for the off-topic question

### ISSUE THREAD

**Issue by denstiny** [lukas-reineke/virt-column.nvim#23]
I noticed the carriage return symbol, is it generated by the plugin?
![图片](https://user-images.githubusercontent.com/57088952/155689852-74687b3e-e3c7-456b-a3c0-cfce4341ec95.png)

**Comment by lukas-reineke** [comment]
No, this is a build in feature. Take a look at `:help list` and `:help listchars`

**Comment by denstiny** [comment]
> 

![图片](https://user-images.githubusercontent.com/57088952/155919996-e174ed3e-0ede-4e77-a8a4-c4632d808120.png)
How did you make empty lines not show carriage return

**Comment by lukas-reineke** [comment]
That is https://github.com/lukas-reineke/indent-blankline.nvim
By default it will overwrite the end of line characters. (it can be turned off with `let g:indent_blankline_show_end_of_line = v:true`)

**Comment by denstiny** [comment]
> 

Thank you very much, I believe you also is a person who pay attention to detail
