### ISSUE TITLE
Interop with cursorline

### ISSUE THREAD

**Issue by thetic** [lukas-reineke/virt-column.nvim#26]
When cursorline is enabled, the virtual text retains the normal background and creates a weird gap in the cursorline.
Can the virtual text keep the cursorline background so they "overlap."

**Comment by lukas-reineke** [comment]
`ColorColumn` highlight takes priority over `CursorLine`, this is a limitation of Neovim.

But it annoyed me as well, so I added `:help virt-column-virtcolumn`. This can completely replace the normal color column.
So you set `colorcolumn` to `""` (which is the default), and instead call `require("virt-column").setup { virtcolumn = "+1" }` with the same values you had in `colorcolumn`
That should get rid of the gap.
