### ISSUE TITLE
Startup slow on extremely large files

### ISSUE THREAD

**Issue by yochem** [lukas-reineke/virt-column.nvim#27]
Hi @lukas-reineke!

When opening a c source file of 600,000 lines (https://github.com/latex-lsp/tree-sitter-latex/blob/master/src/parser.c), I noticed a startup time of 27,138 milliseconds. 7576 ms of these were due to VimEnter autocmds. When I removed the `require('virt-column').setup({})` line from my config, the VimEnter time was around 4 ms.

I get that this normally isn't a problem, but I was wondering if it would be possible to just draw the virtual column line for just the current viewport (I don't know if this is the right word, but I mean the lines currently visible). This would be more like the 'vim-way' of viewing a file.

Let me know what you think! 

Thanks in advance for looking at this issue,
Yochem

**Comment by lukas-reineke** [comment]
Yeah.. I did not expect someone to open files this large.
I thought it would be more efficient to only draw the whole buffer once, and not update on every scroll event.
But I can change it.

**Comment by yochem** [comment]
Maybe it would be possible to have 2 modes; whole buffer and every scroll event and switch modes if the file is larger than, for example, 10000 lines?
