### ISSUE TITLE
Columns not rendering if the editor width is less than columns

### ISSUE THREAD

**Issue by francium** [lukas-reineke/virt-column.nvim#29]
I've been seeing this issue for a while, but I finally realized today what the root cause is.

If the width is less than the column, then the virtual columns won't render until you do `:e` to reload the file.

See the video attached

https://user-images.githubusercontent.com/15352422/190864903-549263b4-2c3d-4810-87bb-65a8c0a7388a.mp4

The obvious solution would be to trigger a virtual column re-render on resize. Does neo(vim) support resize events?

---

EDIT: Looks like there's a feature request for WinResized event, https://github.com/neovim/neovim/issues/11532. There is a VimResized, but that only covers Vim windows resizing. Do you think there's any benefit to redrawing on VimResized or do we need a WinResized for this to be fixed?

**Comment by lukas-reineke** [comment]
I can just remove the check for window size. :+1:
