### ISSUE TITLE
virtcolumn disappears when treesitter is loaded.

### ISSUE THREAD

**Issue by dharmx** [lukas-reineke/virt-column.nvim#32]
Loading treesitter on UIEnter.

https://user-images.githubusercontent.com/80379926/205481025-47360f53-4a32-4bed-b43e-50d71a0daa75.mp4

Loading treesitter manually.

https://user-images.githubusercontent.com/80379926/205481027-4bbedb39-8e99-4dc5-81bf-27a6054d4abf.mp4

Also tried disabling the treesitter modules and plugins as well.

EDIT: Somehow the colorcolumn value gets set to 99999 after loading treesitter.
EDIT: Resetting to 120 (my colorcolumn value) does the trick. But, IDK why this happens :/
EDIT: Currently using `autocmd("InsertEnter", "set colorcolumn=120")`

**Comment by lukas-reineke** [comment]
You can try `:verbose set colorcolumn` to see where it comes from. But this is something in your config, I can't really help you with that.

**Comment by dharmx** [comment]
Ah. That's okay.

**Comment by dharmx** [comment]
I found the thing I needed https://github.com/lukas-reineke/indent-blankline.nvim/issues/59. Apparently, I had vim.wo.colourcolumn = "99999" set haha.
