### ISSUE TITLE
floating toggleterm window shows virt-column

### ISSUE THREAD

**Issue by uloco** [lukas-reineke/virt-column.nvim#36]
I am not sure if this is a configuration issue but when I have a floating terminal by toggleterm, the virt-column shows through it and leaks into the terminal, which is kinda weird.

<img width="1001" alt="Screenshot 2023-06-27 at 14 29 24" src="https://github.com/lukas-reineke/virt-column.nvim/assets/8818340/ab92df72-8d0e-4249-b0b5-a14e1d7e934b">

<img width="1001" alt="Screenshot 2023-06-27 at 14 29 30" src="https://github.com/lukas-reineke/virt-column.nvim/assets/8818340/c10663fc-f938-4a64-9487-668a179a87b9">

**Comment by lukas-reineke** [comment]
you can run `require("virt-column").setup_buffer { virtcolumn = '' }` for terminal buffers to turn it off
