### ISSUE TITLE
`excluded` config isn't honored

### ISSUE THREAD

**Issue by hinell** [lukas-reineke/virt-column.nvim#39]
![image](https://github.com/lukas-reineke/virt-column.nvim/assets/8136158/31b95d09-8381-4aad-ac72-6dd57807f8a6)

Hi. In telescope these lines are still visble.  Config is default:

```lua
use({
	"lukas-reineke/virt-column.nvim",
	config = function()
		-- Extend default virt-column config
		require("virt-column").update({
			virtcolumn = "80, 120"
		})
	end
})

```

**Comment by lukas-reineke** [comment]
I forgot to implement it :man_facepalming: 

should be fixed now
