### ISSUE TITLE
Column Line shows on Startup Page

### ISSUE THREAD

**Issue by frankdoescode** [lukas-reineke/virt-column.nvim#46]
After installing, the Column Line now shows up on the Startup Page for LazyVim. This is very urgent, :)
<img width="1920" alt="Screenshot 2024-10-27 at 9 40 52 PM" src="https://github.com/user-attachments/assets/6a744a56-8c4a-4e32-9d65-f650f4a4d069">

**Comment by lukas-reineke** [comment]
Take a look at `:help virt-column.config.exclude`

**Comment by frankdoescode** [comment]
I've tried 'dashboard', 'Dashboard' and 'dash'. You got any hints?
<img width="1920" alt="Screenshot 2024-10-28 at 2 36 29 PM" src="https://github.com/user-attachments/assets/bedcdaac-477b-4fd1-9142-fa207bd1db30">

**Comment by lukas-reineke** [comment]
`exclude` is a table, it takes `filetypes` and `buftypes`.

```lua
exclude = {
  filetypes = { "foo" },
  buftypes = { "bar" },
}
```

To check what dashboard is using, you can run `:set filetype`, or `:set buftype` while in the dashboard buffer.

**Comment by frankdoescode** [comment]
Holy Moly it WORKED!! Very Cool.
